[advisories]
version = 2

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
  "0BSD",
  "Apache-2.0",
  "LGPL-2.1-or-later",
  "MIT",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
